---
# tasks file for roletemplate

- name: Install casacore deps from std repos
  apt: name={{ item }} update_cache=yes
  with_items: "{{ lookup('file', 'casacore-apt-deps.txt').split() }}"
  become: yes

- name: Add casacore PPA
  apt_repository: repo="ppa:radio-astro/main"
  become: yes

- name: Install casacore from PPA
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items:
    - casacore2
    - casacore-data
    - libcasacore2-dev
  become: yes