# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "casalibsppavm" do |casalibsppavm| end

  config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../tests/test-casalibs-ppa.yml"
    ansible.verbose = "vv"
    ansible.groups = {
      "test" => ["casalibsppavm"],
      }
  end
 
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end
